/**
 * Rules for characters in the game.
 * Each character has a unique ID, a name and a set of features that can be used as clues.
 * The name key and the id key start with an underscore to avoid conflicts with the features keys.
 * The features sets keys start without underscore and is an array of strings.
 */

export default [
  {
    _id: '003fc57b8bf6',
    _name: 'ANDREW',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['APOSTLE', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONOR', 'DISCIPLE', 'HUMILITY'],
  },
  {
    _id: '0242e2081a15',
    _name: 'SILAS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'DISCIPLE', 'HUMILITY', 'PERSEVERANCE'],
  },
  {
    _id: '04c018e95e56',
    _name: 'MORDECAI',
    gender: ['MALE'],
    age: ['EXILE', 'OT'],
    features: [
      'AUTHORITY',
      'BETRAYED',
      'ENCOURAGEMENT',
      'HONOR',
      'PERSECUTED',
      'COURAGE',
      'HONESTY',
      'PERSEVERANCE',
      'WISDOM',
    ],
  },
  {
    _id: '0a6ac060fde8',
    _name: 'MELCHIZEDEK',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: ['KINGSHIP', 'PRIEST', 'HOLINESS', 'HONOR', 'HOSPITALITY', 'WISDOM'],
  },
  {
    _id: '0a765194c58e',
    _name: 'RUTH',
    gender: ['FEMALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'COMMONER',
      'OBEDIENCE',
      'COMPASSION',
      'GENEROSITY',
      'HONOR',
      'DECISION',
      'HUMILITY',
      'PERSEVERANCE',
    ],
  },
  {
    _id: '0b8804f712ba',
    _name: 'JAMES_JOSEPH',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'AMBITION', 'DISCIPLE', 'SACRIFICE'],
  },
  {
    _id: '0bbd73d11212',
    _name: 'BALAAM',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['PROPHET', 'DISOBEDIENCE', 'IDOLATRY', 'BETRAYER', 'MANIPULATION', 'AMBITION'],
  },
  {
    _id: '0d9301a26915',
    _name: 'CALEB',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'AUTHORITY',
      'OBEDIENCE_GOD',
      'ENCOURAGEMENT',
      'HONOR',
      'COURAGE',
      'MIRACLES',
      'PERSEVERANCE',
    ],
  },
  {
    _id: '10c05c683f7d',
    _name: 'JOSEPH_NT',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['COMMONER', 'OBEDIENCE', 'HONOR', 'HUMILITY', 'HONESTY', 'SACRIFICE', 'VISIONS'],
  },
  {
    _id: '1473e65b990d',
    _name: 'SHADRACH',
    gender: ['MALE'],
    age: ['EXILE', 'OT'],
    features: ['GOVERNMENT', 'OBEDIENCE', 'HONOR', 'PERSECUTED', 'COURAGE', 'SACRIFICE'],
  },
  {
    _id: '1558fa7989ac',
    _name: 'REHOBOAM',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'REBELLION',
      'MANIPULATION',
      'AMBITION',
      'FOOLISHNESS',
    ],
  },
  {
    _id: '18d63c3c35d1',
    _name: 'EZRA',
    gender: ['MALE'],
    age: ['EXILE', 'OT'],
    features: ['PRIEST', 'HOLINESS', 'ENCOURAGEMENT', 'HONOR', 'HONESTY', 'PERSEVERANCE', 'WISDOM'],
  },
  {
    _id: '228f5704a5d4',
    _name: 'ACHAN',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['COMMONER', 'DISOBEDIENCE', 'MANIPULATION', 'AMBITION', 'DECISION'],
  },
  {
    _id: '2658e24203f2',
    _name: 'DANIEL',
    gender: ['MALE'],
    age: ['EXILE', 'OT'],
    features: [
      'GOVERNMENT',
      'HOLINESS',
      'HONOR',
      'PERSECUTED',
      'COURAGE',
      'HONESTY',
      'PERSEVERANCE',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    _id: '29ea81d0e0b7',
    _name: 'JOB',
    gender: ['MALE'],
    age: ['ORIGINS', 'OT'],
    features: ['COMMONER', 'DOUBT', 'OBEDIENCE', 'HONOR', 'HONESTY', 'PERSEVERANCE'],
  },
  {
    _id: '30df4e4fcfcd',
    _name: 'JEREMIAH',
    gender: ['MALE'],
    age: ['KINGS', 'EXILE', 'OT'],
    features: [
      'PROPHET',
      'DOUBT',
      'OBEDIENCE',
      'ENCOURAGEMENT',
      'PERSECUTED',
      'PERSEVERANCE',
      'SACRIFICE',
    ],
  },
  {
    _id: '3243634e124d',
    _name: 'THOMAS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['APOSTLE', 'DOUBT', 'OBEDIENCE', 'COURAGE', 'DISCIPLE', 'HONESTY'],
  },
  {
    _id: '33a8bfba05e6',
    _name: 'NATHAN',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['PROPHET', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONOR', 'COURAGE', 'HONESTY', 'WISDOM'],
  },
  {
    _id: '34a6664e8dad',
    _name: 'AARON',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['PRIEST', 'DISOBEDIENCE', 'IDOLATRY', 'HONOR', 'MANIPULATION', 'HUMILITY'],
  },
  {
    _id: '3649f1998ec7',
    _name: 'BARNABAS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'GENEROSITY', 'HONOR'],
  },
  {
    _id: '371cc3ed4281',
    _name: 'AHAB',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'MANIPULATION',
      'PERSECUTOR',
      'AMBITION',
      'FOOLISHNESS',
    ],
  },
  {
    _id: '434eb02d24ad',
    _name: 'KORAH',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['PRIEST', 'DISOBEDIENCE', 'REBELLION', 'MANIPULATION', 'FOOLISHNESS'],
  },
  {
    _id: '4441534c6812',
    _name: 'JEROBOAM',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'REBELLION',
      'BETRAYER',
      'MANIPULATION',
      'AMBITION',
    ],
  },
  {
    _id: '495b93348c1b',
    _name: 'JOSEPH_OT',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'GOVERNMENT',
      'OBEDIENCE',
      'BETRAYED',
      'FORGIVENESS',
      'BEAUTY',
      'HUMILITY',
      'HONESTY',
      'PERSEVERANCE',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    _id: '4a4ae2d79ea7',
    _name: 'ABSALOM',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'REBELLION',
      'BETRAYED',
      'BETRAYER',
      'MANIPULATION',
      'AMBITION',
      'BEAUTY',
    ],
  },
  {
    _id: '4aeccfc45a8e',
    _name: 'PETER',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'APOSTLE',
      'LEADERSHIP',
      'DISOBEDIENCE',
      'DOUBT',
      'OBEDIENCE',
      'REPENTANCE',
      'PERSECUTED',
      'COURAGE',
      'DISCIPLE',
      'MIRACLES',
      'VISIONS',
    ],
  },
  {
    _id: '536ad5ba5670',
    _name: 'LAZARUS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['COMMONER', 'HOSPITALITY', 'DECISION', 'DISCIPLE'],
  },
  {
    _id: '5376b95985f9',
    _name: 'PHARAOH',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'REBELLION',
      'BETRAYER',
      'MANIPULATION',
      'PERSECUTOR',
      'AMBITION',
      'VISIONS',
    ],
  },
  {
    _id: '53e291286051',
    _name: 'OBADIAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['PROPHET', 'OBEDIENCE', 'HONOR', 'COURAGE', 'DECISION'],
  },
  {
    _id: '53e3d4617e44',
    _name: 'HABAKKUK',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'PROPHET',
      'DOUBT',
      'OBEDIENCE',
      'COMPASSION',
      'DECISION',
      'PERSEVERANCE',
      'VISIONS',
    ],
  },
  {
    _id: '571b331c32ad',
    _name: 'ESAU',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'COMMONER',
      'DISOBEDIENCE',
      'BETRAYED',
      'FORGIVENESS',
      'BEAUTY',
      'DECISION',
      'FOOLISHNESS',
    ],
  },
  {
    _id: '5b8de0060b17',
    _name: 'HEZEKIAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'OBEDIENCE',
      'REPENTANCE',
      'FORGIVENESS',
      'HONOR',
      'COURAGE',
      'DECISION',
      'WISDOM',
    ],
  },
  {
    _id: '5eca9cdc4a28',
    _name: 'JUDAS_THADDAEUS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['APOSTLE', 'OBEDIENCE', 'ENCOURAGEMENT', 'COURAGE', 'DISCIPLE', 'PERSEVERANCE'],
  },
  {
    _id: '66cd0dc6cfa7',
    _name: 'CAIAPHAS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'PRIEST',
      'DISOBEDIENCE',
      'REBELLION',
      'BETRAYER',
      'MANIPULATION',
      'PERSECUTOR',
      'AMBITION',
    ],
  },
  {
    _id: '6b634c1b72fe',
    _name: 'AMOS',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['PROPHET', 'HOLINESS', 'COMPASSION', 'HONOR', 'PERSECUTED', 'COURAGE', 'VISIONS'],
  },
  {
    _id: '6d6d333a6395',
    _name: 'APOLLO',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONOR', 'HUMILITY', 'WISDOM'],
  },
  {
    _id: '6d9e91e15d40',
    _name: 'LYDIA',
    gender: ['FEMALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['COMMONER', 'OBEDIENCE', 'ENCOURAGEMENT', 'GENEROSITY', 'HOSPITALITY'],
  },
  {
    _id: '7365794cb3c6',
    _name: 'JOSHUA',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'AUTHORITY',
      'OBEDIENCE',
      'ENCOURAGEMENT',
      'HONOR',
      'COURAGE',
      'DISCIPLE',
      'PERSEVERANCE',
    ],
  },
  {
    _id: '78ef9851a10d',
    _name: 'URIAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['COMMONER', 'OBEDIENCE', 'BETRAYED', 'HONOR', 'HONESTY', 'SACRIFICE'],
  },
  {
    _id: '7a3b0288b09d',
    _name: 'PRISCILLA',
    gender: ['FEMALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'HOSPITALITY', 'DISCIPLE', 'WISDOM'],
  },
  {
    _id: '7d9426c0771f',
    _name: 'JETHRO',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['AUTHORITY', 'OBEDIENCE', 'ENCOURAGEMENT', 'HOSPITALITY', 'WISDOM'],
  },
  {
    _id: '7ea92a302845',
    _name: 'PHILIP',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'APOSTLE',
      'OBEDIENCE',
      'ENCOURAGEMENT',
      'COURAGE',
      'DISCIPLE',
      'HUMILITY',
      'MIRACLES',
      'WISDOM',
    ],
  },
  {
    _id: '7f2e8ad692ec',
    _name: 'TIMOTHY',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONOR', 'DISCIPLE', 'HUMILITY'],
  },
  {
    _id: '83af57c8a569',
    _name: 'MIRIAM',
    gender: ['FEMALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'LEADERSHIP',
      'PROPHET',
      'DISOBEDIENCE',
      'REBELLION',
      'ENCOURAGEMENT',
      'MANIPULATION',
      'COURAGE',
    ],
  },
  {
    _id: '850b694021a0',
    _name: 'JESUS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'LEADERSHIP',
      'HOLINESS',
      'BETRAYED',
      'COMPASSION',
      'ENCOURAGEMENT',
      'FORGIVENESS',
      'PERSECUTED',
      'MIRACLES',
      'SACRIFICE',
      'WISDOM',
    ],
  },
  {
    _id: '851f96ec7f08',
    _name: 'JOHN',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'APOSTLE',
      'HOLINESS',
      'ENCOURAGEMENT',
      'PERSECUTED',
      'AMBITION',
      'COURAGE',
      'DISCIPLE',
      'HUMILITY',
      'SACRIFICE',
      'VISIONS',
    ],
  },
  {
    _id: '8835b91d22f0',
    _name: 'MATTHEW',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'APOSTLE',
      'OBEDIENCE',
      'REPENTANCE',
      'GENEROSITY',
      'HOSPITALITY',
      'DECISION',
      'DISCIPLE',
    ],
  },
  {
    _id: '8854880aa421',
    _name: 'JACOB',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'COMMONER',
      'DISOBEDIENCE',
      'OBEDIENCE',
      'BETRAYER',
      'FORGIVENESS',
      'MANIPULATION',
      'PERSEVERANCE',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    _id: '88e07349ecd3',
    _name: 'NOAH',
    gender: ['MALE'],
    age: ['ORIGINS', 'OT'],
    features: ['COMMONER', 'OBEDIENCE_GOD', 'HONOR', 'DECISION', 'HONESTY', 'PERSEVERANCE'],
  },
  {
    _id: '8a9c07db3235',
    _name: 'ESTHER',
    gender: ['FEMALE'],
    age: ['EXILE', 'OT'],
    features: [
      'KINGSHIP',
      'OBEDIENCE',
      'COMPASSION',
      'MANIPULATION',
      'BEAUTY',
      'COURAGE',
      'DECISION',
      'HUMILITY',
      'PERSEVERANCE',
    ],
  },
  {
    _id: '8cb017e9c0be',
    _name: 'JEZEBEL',
    gender: ['FEMALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'REBELLION',
      'MANIPULATION',
      'PERSECUTOR',
      'SEDUCTION',
      'AMBITION',
    ],
  },
  {
    _id: '8f8f5a1a2006',
    _name: 'DELILAH',
    gender: ['FEMALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'COMMONER',
      'IDOLATRY',
      'BETRAYER',
      'MANIPULATION',
      'SEDUCTION',
      'AMBITION',
      'BEAUTY',
    ],
  },
  {
    _id: '9549412eee2a',
    _name: 'ELIJAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'PROPHET',
      'DOUBT',
      'OBEDIENCE',
      'HONOR',
      'PERSECUTED',
      'COURAGE',
      'HUMILITY',
      'MIRACLES',
      'PERSEVERANCE',
    ],
  },
  {
    _id: '9917fed6d108',
    _name: 'TITUS',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['LEADERSHIP', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONESTY', 'PERSEVERANCE'],
  },
  {
    _id: '9b333f91b78f',
    _name: 'ISAAC',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: ['COMMONER', 'OBEDIENCE', 'HONOR', 'HOSPITALITY', 'SACRIFICE', 'VISIONS'],
  },
  {
    _id: 'a06986d458ed',
    _name: 'MANASSEH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'REPENTANCE',
      'MANIPULATION',
      'FOOLISHNESS',
      'HUMILITY',
    ],
  },
  {
    _id: 'aa751bf3a519',
    _name: 'AQUILA',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['COMMONER', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONOR', 'HOSPITALITY'],
  },
  {
    _id: 'ab31873de208',
    _name: 'BARTHOLOMEW',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['APOSTLE', 'OBEDIENCE', 'HONOR', 'PERSECUTED', 'DISCIPLE', 'HONESTY'],
  },
  {
    _id: 'ab7fae8051b1',
    _name: 'EZEKIEL',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['PRIEST', 'HOLINESS', 'HONOR', 'PERSECUTED', 'PERSEVERANCE', 'VISIONS'],
  },
  {
    _id: 'b00d1b737b0e',
    _name: 'SAUL',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'REBELLION',
      'PERSECUTOR',
      'AMBITION',
      'BEAUTY',
      'FOOLISHNESS',
    ],
  },
  {
    _id: 'b8436d32b85a',
    _name: 'BATHSHEBA',
    gender: ['FEMALE'],
    age: ['KINGS', 'OT'],
    features: ['KINGSHIP', 'REPENTANCE', 'MANIPULATION', 'SEDUCTION', 'BEAUTY', 'DECISION'],
  },
  {
    _id: 'b9b37969a172',
    _name: 'ABRAHAM',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'COMMONER',
      'DOUBT',
      'OBEDIENCE_GOD',
      'GENEROSITY',
      'HONOR',
      'HOSPITALITY',
      'COURAGE',
      'HUMILITY',
      'PERSEVERANCE',
      'SACRIFICE',
    ],
  },
  {
    _id: 'bab6c7139112',
    _name: 'PILATE',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['GOVERNMENT', 'DISOBEDIENCE', 'MANIPULATION', 'DECISION'],
  },
  {
    _id: 'bac28d102b32',
    _name: 'DAVID',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'OBEDIENCE',
      'REPENTANCE',
      'BETRAYED',
      'BETRAYER',
      'FORGIVENESS',
      'PERSECUTED',
      'BEAUTY',
      'COURAGE',
      'PERSEVERANCE',
    ],
  },
  {
    _id: 'bb7b310e6e56',
    _name: 'REBEKAH',
    gender: ['FEMALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'COMMONER',
      'DISOBEDIENCE',
      'HOSPITALITY',
      'MANIPULATION',
      'BEAUTY',
      'DECISION',
      'HUMILITY',
    ],
  },
  {
    _id: 'be620be58de8',
    _name: 'ZERUBBABEL',
    gender: ['MALE'],
    age: ['EXILE', 'OT'],
    features: ['GOVERNMENT', 'OBEDIENCE', 'HONOR', 'COURAGE', 'DECISION', 'PERSEVERANCE'],
  },
  {
    _id: 'bedbe915403a',
    _name: 'LOT',
    gender: ['MALE'],
    age: ['PATRIARCHS', 'OT'],
    features: [
      'COMMONER',
      'DISOBEDIENCE',
      'OBEDIENCE_GOD',
      'HOSPITALITY',
      'DECISION',
      'FOOLISHNESS',
    ],
  },
  {
    _id: 'bf751829bd49',
    _name: 'GIDEON',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'AUTHORITY',
      'DOUBT',
      'IDOLATRY',
      'OBEDIENCE_GOD',
      'ENCOURAGEMENT',
      'HONOR',
      'COURAGE',
      'HUMILITY',
      'MIRACLES',
    ],
  },
  {
    _id: 'c312c8d5b648',
    _name: 'PHILEMON',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['COMMONER', 'OBEDIENCE', 'FORGIVENESS', 'GENEROSITY', 'HOSPITALITY', 'WISDOM'],
  },
  {
    _id: 'c619bc235498',
    _name: 'ISAIAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'PROPHET',
      'HOLINESS',
      'COMPASSION',
      'HONOR',
      'PERSECUTED',
      'HUMILITY',
      'MIRACLES',
      'PERSEVERANCE',
    ],
  },
  {
    _id: 'c723b0cece2b',
    _name: 'EVE',
    gender: ['FEMALE'],
    age: ['ORIGINS', 'OT'],
    features: ['COMMONER', 'DISOBEDIENCE', 'MANIPULATION', 'AMBITION', 'BEAUTY', 'DECISION'],
  },
  {
    _id: 'c9260283e598',
    _name: 'SARAH',
    gender: ['FEMALE'],
    age: ['PATRIARCHS', 'OT'],
    features: ['COMMONER', 'DOUBT', 'HOSPITALITY', 'BEAUTY', 'PERSEVERANCE'],
  },
  {
    _id: 'c93153fbd2ec',
    _name: 'SAMSON',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'AUTHORITY',
      'DISOBEDIENCE',
      'REPENTANCE',
      'BETRAYED',
      'COURAGE',
      'FOOLISHNESS',
      'SACRIFICE',
    ],
  },
  {
    _id: 'd1223a82ed11',
    _name: 'HAGGAI',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['PROPHET', 'HOLINESS', 'ENCOURAGEMENT', 'HONOR', 'DECISION', 'WISDOM'],
  },
  {
    _id: 'd1a4727fefac',
    _name: 'RAHAB',
    gender: ['FEMALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['COMMONER', 'OBEDIENCE', 'COMPASSION', 'HOSPITALITY', 'BEAUTY', 'COURAGE'],
  },
  {
    _id: 'd66502bad9b3',
    _name: 'MOSES',
    gender: ['MALE'],
    age: ['THEOCRACY', 'OT'],
    features: [
      'AUTHORITY',
      'DISOBEDIENCE',
      'DOUBT',
      'OBEDIENCE_GOD',
      'COMPASSION',
      'ENCOURAGEMENT',
      'DECISION',
      'MIRACLES',
    ],
  },
  {
    _id: 'd713449b7477',
    _name: 'PAUL',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'APOSTLE',
      'LEADERSHIP',
      'DISOBEDIENCE',
      'OBEDIENCE',
      'REPENTANCE',
      'ENCOURAGEMENT',
      'PERSECUTED',
      'COURAGE',
      'MIRACLES',
      'PERSEVERANCE',
      'VISIONS',
    ],
  },
  {
    _id: 'd772d2b0ad91',
    _name: 'SOLOMON',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'KINGSHIP',
      'DISOBEDIENCE',
      'IDOLATRY',
      'GENEROSITY',
      'BEAUTY',
      'DECISION',
      'WISDOM',
    ],
  },
  {
    _id: 'd8126ec3a1a1',
    _name: 'ZECHARIAH',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['PRIEST', 'DOUBT', 'OBEDIENCE_GOD', 'PERSEVERANCE', 'VISIONS'],
  },
  {
    _id: 'dce604085342',
    _name: 'MARTHA',
    gender: ['FEMALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['COMMONER', 'DOUBT', 'GENEROSITY', 'HOSPITALITY', 'DISCIPLE'],
  },
  {
    _id: 'dd28adb09f3d',
    _name: 'STEPHEN',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'LEADERSHIP',
      'HOLINESS',
      'FORGIVENESS',
      'PERSECUTED',
      'COURAGE',
      'DISCIPLE',
      'HUMILITY',
      'PERSEVERANCE',
      'SACRIFICE',
    ],
  },
  {
    _id: 'e1c769752ded',
    _name: 'JONAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'PROPHET',
      'DISOBEDIENCE',
      'OBEDIENCE_GOD',
      'REPENTANCE',
      'ENCOURAGEMENT',
      'DECISION',
      'FOOLISHNESS',
    ],
  },
  {
    _id: 'e21370e773f1',
    _name: 'JOSIAH',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: ['KINGSHIP', 'IDOLATRY', 'OBEDIENCE', 'REPENTANCE', 'HONESTY', 'WISDOM'],
  },
  {
    _id: 'e61abe6f3157',
    _name: 'MARY_MAGDALENE',
    gender: ['FEMALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'COMMONER',
      'REPENTANCE',
      'COMPASSION',
      'GENEROSITY',
      'DISCIPLE',
      'HUMILITY',
      'PERSEVERANCE',
    ],
  },
  {
    _id: 'e778ff0452e5',
    _name: 'NEHEMIAH',
    gender: ['MALE'],
    age: ['EXILE', 'OT'],
    features: ['GOVERNMENT', 'OBEDIENCE', 'ENCOURAGEMENT', 'GENEROSITY', 'HONESTY', 'PERSEVERANCE'],
  },
  {
    _id: 'e7b003f6705e',
    _name: 'ELISHA',
    gender: ['MALE'],
    age: ['KINGS', 'OT'],
    features: [
      'PROPHET',
      'OBEDIENCE',
      'COMPASSION',
      'HOSPITALITY',
      'PERSECUTED',
      'DISCIPLE',
      'MIRACLES',
      'PERSEVERANCE',
      'WISDOM',
    ],
  },
  {
    _id: 'e97756041a8b',
    _name: 'DEBORAH',
    gender: ['FEMALE'],
    age: ['THEOCRACY', 'OT'],
    features: ['AUTHORITY', 'OBEDIENCE', 'ENCOURAGEMENT', 'HONOR', 'COURAGE', 'WISDOM'],
  },
  {
    _id: 'ecab39db05b8',
    _name: 'SIMON_ZEALOT',
    gender: ['MALE'],
    age: ['REDEMPTION', 'NT'],
    features: ['APOSTLE', 'OBEDIENCE', 'HONOR', 'DISCIPLE', 'PERSEVERANCE'],
  },
  {
    _id: 'efc9ddc1f6cc',
    _name: 'MARY',
    gender: ['FEMALE'],
    age: ['REDEMPTION', 'NT'],
    features: [
      'COMMONER',
      'HOLINESS',
      'COMPASSION',
      'HONOR',
      'DECISION',
      'HUMILITY',
      'PERSEVERANCE',
    ],
  },
  {
    _id: 'fd5e94014a42',
    _name: 'SAMUEL',
    gender: ['MALE'],
    age: ['THEOCRACY', 'KINGS', 'OT'],
    features: [
      'AUTHORITY',
      'PRIEST',
      'PROPHET',
      'HOLINESS',
      'ENCOURAGEMENT',
      'HONOR',
      'COURAGE',
      'HONESTY',
    ],
  },
  {
    _id: 'ffb36ebe8c34',
    _name: 'ADAM',
    gender: ['MALE'],
    age: ['ORIGINS', 'OT'],
    features: ['COMMONER', 'DISOBEDIENCE', 'REPENTANCE', 'MANIPULATION', 'AMBITION', 'DECISION'],
  },
]
