const persons = [
  {
    id: '003fc57b8bf6',
    name: 'ANDREW',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'ENCOURAGEMENT', 'HUMILITY'],
  },
  {
    id: '0242e2081a15',
    name: 'SILAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLE', 'ENCOURAGEMENT', 'HUMILITY', 'LEADERSHIP', 'PERSEVERANCE'],
  },
  {
    id: '04c018e95e56',
    name: 'MORDECAI',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'COMMITMENT',
      'COURAGE',
      'ENCOURAGEMENT',
      'HONESTY',
      'HONOR',
      'PERSEVERANCE',
      'WISDOM',
    ],
  },
  {
    id: '0a6ac060fde8',
    name: 'MELCHIZEDEK',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'HOLINESS', 'HONOR', 'HOSPITALITY', 'WISDOM'],
  },
  {
    id: '0a765194c58e',
    name: 'RUTH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: [
      'COMMITMENT',
      'COMPASSION',
      'DECISION',
      'GENEROSITY',
      'HONOR',
      'HUMILITY',
      'PERSEVERANCE',
    ],
  },
  {
    id: '0b8804f712ba',
    name: 'JAMES',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AMBITION', 'DISCIPLE', 'HOLINESS', 'LEADERSHIP', 'SACRIFICE'],
  },
  {
    id: '0bbd73d11212',
    name: 'BALAAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'DISOBEDIENCE', 'MANIPULATION', 'PROPHET'],
  },
  {
    id: '0d9301a26915',
    name: 'CALEB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'COURAGE', 'ENCOURAGEMENT', 'HONOR', 'PERSEVERANCE'],
  },
  {
    id: '10c05c683f7d',
    name: 'JOSEPH_NT',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['HOLINESS', 'HONESTY', 'HONOR', 'HUMILITY', 'SACRIFICE', 'VISIONS'],
  },
  {
    id: '1473e65b990d',
    name: 'SHADRACH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'COURAGE', 'HONOR', 'PERSEVERANCE', 'SACRIFICE'],
  },
  {
    id: '1558fa7989ac',
    name: 'REHOBOAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'DISOBEDIENCE', 'FOOLISHNESS', 'IDOLATRY', 'KINGSHIP'],
  },
  {
    id: '18d63c3c35d1',
    name: 'EZRA',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'ENCOURAGEMENT', 'HONESTY', 'PERSEVERANCE', 'PRIEST', 'WISDOM'],
  },
  {
    id: '228f5704a5d4',
    name: 'ACHAN',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AMBITION',
      'CONFLICT',
      'DECISION',
      'DISOBEDIENCE',
      'IDOLATRY',
      'LEADERSHIP',
      'MANIPULATION',
      'REBELLION',
    ],
  },
  {
    id: '2658e24203f2',
    name: 'DANIEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'COMMITMENT',
      'COURAGE',
      'HOLINESS',
      'HONESTY',
      'HONOR',
      'PERSEVERANCE',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    id: '29ea81d0e0b7',
    name: 'JOB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DOUBT', 'HONESTY', 'HONOR', 'PERSEVERANCE'],
  },
  {
    id: '30df4e4fcfcd',
    name: 'JEREMIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'PERSEVERANCE', 'PROPHET', 'SACRIFICE'],
  },
  {
    id: '3243634e124d',
    name: 'THOMAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COURAGE', 'DISCIPLE', 'DOUBT', 'HONESTY'],
  },
  {
    id: '33a8bfba05e6',
    name: 'NATHAN',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COURAGE', 'ENCOURAGEMENT', 'HONESTY', 'HONOR', 'PROPHET', 'WISDOM'],
  },
  {
    id: '34a6664e8dad',
    name: 'AARON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['ENCOURAGEMENT', 'HUMILITY', 'IDOLATRY', 'PRIEST'],
  },
  {
    id: '3649f1998ec7',
    name: 'BARNABAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMPASSION', 'ENCOURAGEMENT', 'GENEROSITY', 'HOSPITALITY', 'LEADERSHIP'],
  },
  {
    id: '371cc3ed4281',
    name: 'AHAB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'DISOBEDIENCE', 'IDOLATRY', 'KINGSHIP', 'MANIPULATION'],
  },
  {
    id: '434eb02d24ad',
    name: 'KORAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['CONFLICT', 'DISOBEDIENCE', 'FOOLISHNESS', 'IDOLATRY', 'MANIPULATION', 'REBELLION'],
  },
  {
    id: '4441534c6812',
    name: 'JEROBOAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'DISOBEDIENCE', 'IDOLATRY', 'KINGSHIP', 'REBELLION'],
  },
  {
    id: '495b93348c1b',
    name: 'JOSEPH_OT',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'COMMITMENT',
      'FORGIVENESS',
      'HONESTY',
      'HUMILITY',
      'PERSEVERANCE',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    id: '4a4ae2d79ea7',
    name: 'ABSALOM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AMBITION',
      'BEAUTY',
      'CONFLICT',
      'DISOBEDIENCE',
      'KINGSHIP',
      'MANIPULATION',
      'REBELLION',
    ],
  },
  {
    id: '4aeccfc45a8e',
    name: 'PETER',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'AUTHORITY',
      'COMMITMENT',
      'CONFLICT',
      'COURAGE',
      'DISCIPLE',
      'DOUBT',
      'MIRACLES',
      'VISIONS',
    ],
  },
  {
    id: '536ad5ba5670',
    name: 'LAZARUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DECISION', 'DISCIPLE', 'HOSPITALITY'],
  },
  {
    id: '5376b95985f9',
    name: 'PHARAOH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'DISOBEDIENCE', 'IDOLATRY', 'KINGSHIP', 'VISIONS'],
  },
  {
    id: '53e291286051',
    name: 'OBADIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'COURAGE', 'PROPHET'],
  },
  {
    id: '53e3d4617e44',
    name: 'HABAKKUK',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DECISION', 'DOUBT', 'PERSEVERANCE', 'PROPHET', 'VISIONS'],
  },
  {
    id: '571b331c32ad',
    name: 'ESAU',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'CONFLICT',
      'DECISION',
      'DISOBEDIENCE',
      'FOOLISHNESS',
      'FORGIVENESS',
    ],
  },
  {
    id: '5b8de0060b17',
    name: 'HEZEKIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'COURAGE', 'DECISION', 'KINGSHIP', 'WISDOM'],
  },
  {
    id: '5eca9cdc4a28',
    name: 'JUDAS_THADDAEUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COURAGE', 'DISCIPLE', 'PERSEVERANCE'],
  },
  {
    id: '66cd0dc6cfa7',
    name: 'CAIAPHAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AMBITION', 'CONFLICT', 'MANIPULATION', 'PRIEST'],
  },
  {
    id: '6b634c1b72fe',
    name: 'AMOS',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMPASSION', 'CONFLICT', 'COURAGE', 'PROPHET', 'VISIONS'],
  },
  {
    id: '6d6d333a6395',
    name: 'APOLLOS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['ENCOURAGEMENT', 'HUMILITY', 'LEADERSHIP', 'WISDOM'],
  },
  {
    id: '6d9e91e15d40',
    name: 'LYDIA',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COMPASSION', 'ENCOURAGEMENT', 'GENEROSITY', 'HOSPITALITY'],
  },
  {
    id: '7365794cb3c6',
    name: 'JOSHUA',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'COMMITMENT',
      'CONFLICT',
      'COURAGE',
      'DECISION',
      'HONOR',
      'MIRACLES',
      'PERSEVERANCE',
    ],
  },
  {
    id: '78ef9851a10d',
    name: 'URIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'HONESTY', 'HONOR', 'SACRIFICE'],
  },
  {
    id: '7a3b0288b09d',
    name: 'PRISCILLA',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'ENCOURAGEMENT', 'GENEROSITY', 'HOSPITALITY', 'WISDOM'],
  },
  {
    id: '7d9426c0771f',
    name: 'JETHRO',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'ENCOURAGEMENT', 'HOSPITALITY', 'WISDOM'],
  },
  {
    id: '7ea92a302845',
    name: 'PHILIP',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COURAGE', 'DISCIPLE', 'MIRACLES'],
  },
  {
    id: '7f2e8ad692ec',
    name: 'TIMOTHY',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'ENCOURAGEMENT', 'HOLINESS', 'HUMILITY'],
  },
  {
    id: '83af57c8a569',
    name: 'MIRIAM',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['COURAGE', 'DISOBEDIENCE', 'LEADERSHIP', 'PROPHET', 'REBELLION'],
  },
  {
    id: '850b694021a0',
    name: 'JESUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'COMPASSION',
      'ENCOURAGEMENT',
      'FORGIVENESS',
      'GENEROSITY',
      'LEADERSHIP',
      'MIRACLES',
      'SACRIFICE',
      'WISDOM',
    ],
  },
  {
    id: '851f96ec7f08',
    name: 'JOHN',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'AMBITION',
      'COMMITMENT',
      'COURAGE',
      'DISCIPLE',
      'HOLINESS',
      'HUMILITY',
      'SACRIFICE',
      'VISIONS',
    ],
  },
  {
    id: '8835b91d22f0',
    name: 'MATTHEW',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DECISION', 'DISCIPLE', 'GENEROSITY', 'HOSPITALITY'],
  },
  {
    id: '8854880aa421',
    name: 'JACOB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'CONFLICT',
      'DOUBT',
      'FORGIVENESS',
      'MANIPULATION',
      'PERSEVERANCE',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    id: '88e07349ecd3',
    name: 'NOAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'DECISION', 'HOLINESS', 'HONESTY', 'HONOR', 'PERSEVERANCE'],
  },
  {
    id: '8a9c07db3235',
    name: 'ESTHER',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: [
      'BEAUTY',
      'COMPASSION',
      'COURAGE',
      'DECISION',
      'HUMILITY',
      'KINGSHIP',
      'PERSEVERANCE',
    ],
  },
  {
    id: '8cb017e9c0be',
    name: 'JEZEBEL',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'IDOLATRY', 'KINGSHIP', 'MANIPULATION'],
  },
  {
    id: '8f8f5a1a2006',
    name: 'DELILAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'BEAUTY', 'CONFLICT', 'MANIPULATION'],
  },
  {
    id: '9549412eee2a',
    name: 'ELIJAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'COMMITMENT',
      'CONFLICT',
      'COURAGE',
      'HOLINESS',
      'HONOR',
      'HUMILITY',
      'MIRACLES',
      'PERSEVERANCE',
      'PROPHET',
    ],
  },
  {
    id: '9917fed6d108',
    name: 'TITUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AUTHORITY', 'COMMITMENT', 'ENCOURAGEMENT', 'HONESTY', 'PERSEVERANCE'],
  },
  {
    id: '9b333f91b78f',
    name: 'ISAAC',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'COMPASSION',
      'DOUBT',
      'GENEROSITY',
      'HOSPITALITY',
      'SACRIFICE',
      'VISIONS',
    ],
  },
  {
    id: 'a06986d458ed',
    name: 'MANASSEH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DISOBEDIENCE', 'FOOLISHNESS', 'IDOLATRY', 'KINGSHIP'],
  },
  {
    id: 'aa751bf3a519',
    name: 'AQUILA',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'GENEROSITY', 'HOSPITALITY', 'LEADERSHIP'],
  },
  {
    id: 'ab31873de208',
    name: 'BARTHOLOMEW',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'DOUBT', 'HONESTY'],
  },
  {
    id: 'ab7fae8051b1',
    name: 'EZEKIEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'PERSEVERANCE', 'PRIEST', 'VISIONS'],
  },
  {
    id: 'b00d1b737b0e',
    name: 'SAUL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AMBITION',
      'BEAUTY',
      'CONFLICT',
      'DISOBEDIENCE',
      'FOOLISHNESS',
      'IDOLATRY',
      'KINGSHIP',
    ],
  },
  {
    id: 'b8436d32b85a',
    name: 'BATHSHEBA',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'CONFLICT', 'KINGSHIP', 'MANIPULATION'],
  },
  {
    id: 'b9b37969a172',
    name: 'ABRAHAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'COURAGE',
      'DOUBT',
      'GENEROSITY',
      'HUMILITY',
      'PERSEVERANCE',
      'SACRIFICE',
    ],
  },
  {
    id: 'bab6c7139112',
    name: 'PILATE',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AUTHORITY', 'CONFLICT', 'DECISION', 'DOUBT'],
  },
  {
    id: 'bac28d102b32',
    name: 'DAVID',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'COURAGE',
      'FORGIVENESS',
      'HONESTY',
      'KINGSHIP',
      'LEADERSHIP',
      'PERSEVERANCE',
    ],
  },
  {
    id: 'bb7b310e6e56',
    name: 'REBEKAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'DECISION', 'DOUBT', 'HOSPITALITY', 'HUMILITY', 'MANIPULATION'],
  },
  {
    id: 'be620be58de8',
    name: 'ZERUBBABEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'CONFLICT', 'ENCOURAGEMENT', 'PERSEVERANCE'],
  },
  {
    id: 'bedbe915403a',
    name: 'LOT',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DECISION', 'DISOBEDIENCE', 'FOOLISHNESS', 'HOSPITALITY'],
  },
  {
    id: 'bf751829bd49',
    name: 'GIDEON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'CONFLICT', 'COURAGE', 'DOUBT', 'HUMILITY', 'IDOLATRY', 'MIRACLES'],
  },
  {
    id: 'c312c8d5b648',
    name: 'PHILEMON',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['FORGIVENESS', 'GENEROSITY', 'HOSPITALITY', 'WISDOM'],
  },
  {
    id: 'c619bc235498',
    name: 'ISAIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'COMMITMENT',
      'ENCOURAGEMENT',
      'HOLINESS',
      'HUMILITY',
      'MIRACLES',
      'PERSEVERANCE',
      'PROPHET',
    ],
  },
  {
    id: 'c723b0cece2b',
    name: 'EVE',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'BEAUTY', 'CONFLICT', 'DECISION', 'DISOBEDIENCE', 'REBELLION'],
  },
  {
    id: 'c9260283e598',
    name: 'SARAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'DOUBT', 'HOSPITALITY', 'PERSEVERANCE'],
  },
  {
    id: 'c93153fbd2ec',
    name: 'SAMSON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'CONFLICT',
      'COURAGE',
      'DISOBEDIENCE',
      'FOOLISHNESS',
      'IDOLATRY',
      'SACRIFICE',
    ],
  },
  {
    id: 'd1223a82ed11',
    name: 'HAGGAI',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DECISION', 'ENCOURAGEMENT', 'PROPHET', 'WISDOM'],
  },
  {
    id: 'd1a4727fefac',
    name: 'RAHAB',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'COMPASSION', 'COURAGE', 'HOSPITALITY'],
  },
  {
    id: 'd66502bad9b3',
    name: 'MOSES',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'COMPASSION',
      'DECISION',
      'DOUBT',
      'ENCOURAGEMENT',
      'HOLINESS',
      'MIRACLES',
    ],
  },
  {
    id: 'd713449b7477',
    name: 'PAUL',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'COMMITMENT',
      'COURAGE',
      'DISCIPLE',
      'ENCOURAGEMENT',
      'LEADERSHIP',
      'MIRACLES',
      'PERSEVERANCE',
      'VISIONS',
    ],
  },
  {
    id: 'd772d2b0ad91',
    name: 'SOLOMON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'DECISION', 'GENEROSITY', 'IDOLATRY', 'KINGSHIP', 'WISDOM'],
  },
  {
    id: 'd8126ec3a1a1',
    name: 'ZECHARIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DOUBT', 'PERSEVERANCE', 'PRIEST', 'VISIONS'],
  },
  {
    id: 'dce604085342',
    name: 'MARTHA',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'GENEROSITY', 'HOSPITALITY'],
  },
  {
    id: 'dd28adb09f3d',
    name: 'STEPHEN',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'COMMITMENT',
      'COURAGE',
      'DISCIPLE',
      'FORGIVENESS',
      'HOLINESS',
      'HUMILITY',
      'PERSEVERANCE',
      'SACRIFICE',
      'VISIONS',
    ],
  },
  {
    id: 'e1c769752ded',
    name: 'JONAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DECISION', 'DISOBEDIENCE', 'DOUBT', 'ENCOURAGEMENT', 'FOOLISHNESS', 'PROPHET'],
  },
  {
    id: 'e21370e773f1',
    name: 'JOSIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['ENCOURAGEMENT', 'HONESTY', 'KINGSHIP', 'WISDOM'],
  },
  {
    id: 'e61abe6f3157',
    name: 'MARY_MAGDALENE',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COMPASSION', 'DISCIPLE', 'GENEROSITY', 'HUMILITY', 'PERSEVERANCE'],
  },
  {
    id: 'e778ff0452e5',
    name: 'NEHEMIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'COMMITMENT',
      'CONFLICT',
      'ENCOURAGEMENT',
      'GENEROSITY',
      'HONESTY',
      'PERSEVERANCE',
    ],
  },
  {
    id: 'e7b003f6705e',
    name: 'ELISHA',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'COMPASSION',
      'DISCIPLE',
      'ENCOURAGEMENT',
      'HOLINESS',
      'MIRACLES',
      'PERSEVERANCE',
      'PROPHET',
      'WISDOM',
    ],
  },
  {
    id: 'e97756041a8b',
    name: 'DEBORAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['CONFLICT', 'COURAGE', 'ENCOURAGEMENT', 'WISDOM'],
  },
  {
    id: 'ecab39db05b8',
    name: 'SIMON_ZEALOT',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COURAGE', 'DISCIPLE', 'HONOR', 'PERSEVERANCE'],
  },
  {
    id: 'efc9ddc1f6cc',
    name: 'MARY',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: [
      'COMMITMENT',
      'COMPASSION',
      'DECISION',
      'DOUBT',
      'HOLINESS',
      'HONOR',
      'HUMILITY',
      'PERSEVERANCE',
    ],
  },
  {
    id: 'fcdf44491532',
    name: 'ANNAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AMBITION', 'CONFLICT', 'MANIPULATION', 'PRIEST'],
  },
  {
    id: 'fd5e94014a42',
    name: 'SAMUEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'COURAGE', 'HOLINESS', 'HONESTY', 'PRIEST', 'PROPHET'],
  },
  {
    id: 'ffb36ebe8c34',
    name: 'ADAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'CONFLICT', 'DECISION', 'DISOBEDIENCE', 'REBELLION'],
  },
]

export { persons }
