const persons = [
  {
    id: '34a6664e8dad',
    name: 'AARON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BLESSING',
      'COUNSEL',
      'LEADERSHIP',
      'PRIESTHOOD',
      'PROPHECY',
      'SUPPORT',
    ],
  },
  {
    id: 'f5f162104a75',
    name: 'ABEDNEGO',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'COURAGE', 'DELIVERANCE', 'LOYALTY'],
  },
  {
    id: 'b9b37969a172',
    name: 'ABRAHAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BLESSING',
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'COUNSEL',
      'COURAGE',
      'DECISION',
      'DELIVERANCE',
      'LEADERSHIP',
      'OBEDIENCE',
      'PROPHECY',
      'VISIONS',
    ],
  },
  {
    id: '4a4ae2d79ea7',
    name: 'ABSALOM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AMBITION',
      'AUTHORITY',
      'BEAUTY',
      'BETRAYAL',
      'CHARISMA',
      'CONFLICT',
      'KINGSHIP',
      'REBELLION',
    ],
  },
  {
    id: '228f5704a5d4',
    name: 'ACHAN',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BETRAYAL', 'CONFLICT', 'DECISION', 'DISOBEDIENCE', 'GREED'],
  },
  {
    id: 'ffb36ebe8c34',
    name: 'ADAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'BLESSING', 'DECISION', 'HUMANITY'],
  },
  {
    id: '371cc3ed4281',
    name: 'AHAB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'AUTHORITY', 'CONFLICT', 'IDOLATRY', 'KINGSHIP', 'POWER', 'WEAKNESS'],
  },
  {
    id: '6b634c1b72fe',
    name: 'AMOS',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['JUSTICE', 'PROPHECY', 'VISIONS'],
  },
  {
    id: '003fc57b8bf6',
    name: 'ANDREW',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'EVANGELISM', 'LOYALTY'],
  },
  {
    id: 'fcdf44491532',
    name: 'ANNAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AMBITION', 'AUTHORITY', 'POLITICS', 'PRIESTHOOD', 'RELIGION'],
  },
  {
    id: '6d6d333a6395',
    name: 'APOLLOS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['CHARISMA', 'COUNSEL', 'ELOQUENCE', 'TEACHING'],
  },
  {
    id: 'aa751bf3a519',
    name: 'AQUILA',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'PARTNERSHIP', 'WORK'],
  },
  {
    id: '0bbd73d11212',
    name: 'BALAAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BETRAYAL', 'CONFLICT', 'GREED', 'PROPHECY'],
  },
  {
    id: '3649f1998ec7',
    name: 'BARNABAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['CHARISMA', 'COMPASSION', 'COUNSEL', 'ENCOURAGEMENT', 'MISSION'],
  },
  {
    id: 'ab31873de208',
    name: 'BARTHOLOMEW',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLE', 'HONESTY', 'LOYALTY'],
  },
  {
    id: 'b8436d32b85a',
    name: 'BATHSHEBA',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY'],
  },
  {
    id: '66cd0dc6cfa7',
    name: 'CAIAPHAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AMBITION', 'AUTHORITY', 'BETRAYAL', 'CONFLICT', 'POWER', 'PRIESTHOOD', 'RELIGION'],
  },
  {
    id: '0d9301a26915',
    name: 'CALEB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'COMMITMENT', 'CONFLICT', 'COURAGE', 'LOYALTY'],
  },
  {
    id: '2658e24203f2',
    name: 'DANIEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'COMMITMENT',
      'COUNSEL',
      'COURAGE',
      'DECISION',
      'DELIVERANCE',
      'PROPHECY',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    id: 'bac28d102b32',
    name: 'DAVID',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'BLESSING',
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'CONFLICT',
      'COUNSEL',
      'COURAGE',
      'DECISION',
      'KINGSHIP',
      'LEADERSHIP',
      'LOYALTY',
      'REPENTANCE',
    ],
  },
  {
    id: 'e97756041a8b',
    name: 'DEBORAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'CHARISMA',
      'CONFLICT',
      'COUNSEL',
      'COURAGE',
      'DELIVERANCE',
      'LEADERSHIP',
      'PROPHECY',
      'WISDOM',
    ],
  },
  {
    id: '8f8f5a1a2006',
    name: 'DELILAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'BEAUTY', 'BETRAYAL'],
  },
  {
    id: '9549412eee2a',
    name: 'ELIJAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['CHARISMA', 'COMMITMENT', 'CONFLICT', 'COURAGE', 'PROPHECY'],
  },
  {
    id: 'e7b003f6705e',
    name: 'ELISHA',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMPASSION', 'DISCIPLE', 'MIRACLES', 'PROPHECY'],
  },
  {
    id: '571b331c32ad',
    name: 'ESAU',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'CONFLICT', 'DECISION', 'IMPULSIVENESS', 'LOSS'],
  },
  {
    id: '8a9c07db3235',
    name: 'ESTHER',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'COURAGE',
      'DECISION',
      'DELIVERANCE',
      'KINGSHIP',
      'LEADERSHIP',
      'WISDOM',
    ],
  },
  {
    id: 'c723b0cece2b',
    name: 'EVE',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'BLESSING', 'DECISION', 'HUMANITY', 'TEMPTATION'],
  },
  {
    id: 'ab7fae8051b1',
    name: 'EZEKIEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['OBEDIENCE', 'PRIESTHOOD', 'PROPHECY', 'VISIONS'],
  },
  {
    id: '18d63c3c35d1',
    name: 'EZRA',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'COUNSEL', 'LAW', 'PRIESTHOOD', 'TEACHING'],
  },
  {
    id: 'bf751829bd49',
    name: 'GIDEON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'CHARISMA', 'CONFLICT', 'COURAGE', 'DELIVERANCE', 'DOUBT'],
  },
  {
    id: '53e3d4617e44',
    name: 'HABAKKUK',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['PROPHECY', 'QUESTIONING'],
  },
  {
    id: 'd1223a82ed11',
    name: 'HAGGAI',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['MOTIVATION', 'PROPHECY'],
  },
  {
    id: '5b8de0060b17',
    name: 'HEZEKIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'KINGSHIP', 'PRAYER', 'REFORM'],
  },
  {
    id: '9b333f91b78f',
    name: 'ISAAC',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BLESSING', 'COMPASSION', 'OBEDIENCE', 'PEACEFULNESS', 'VISIONS'],
  },
  {
    id: 'c619bc235498',
    name: 'ISAIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'HOLINESS', 'PROPHECY', 'VISIONS'],
  },
  {
    id: '8854880aa421',
    name: 'JACOB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BLESSING', 'CONFLICT', 'TRANSFORMATION', 'VISIONS'],
  },
  {
    id: '0b8804f712ba',
    name: 'JAMES',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AMBITION', 'DISCIPLE', 'LEADERSHIP', 'MARTYRDOM'],
  },
  {
    id: '30df4e4fcfcd',
    name: 'JEREMIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'PERSEVERANCE', 'PRIESTHOOD', 'PROPHECY', 'SORROW'],
  },
  {
    id: '4441534c6812',
    name: 'JEROBOAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'CONFLICT', 'IDOLATRY', 'KINGSHIP', 'POWER', 'REBELLION'],
  },
  {
    id: '850b694021a0',
    name: 'JESUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'AUTHORITY',
      'BLESSING',
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'COUNSEL',
      'COURAGE',
      'HOLINESS',
      'LEADERSHIP',
      'LOVE',
      'PRIESTHOOD',
      'SACRIFICE',
      'WISDOM',
    ],
  },
  {
    id: '7d9426c0771f',
    name: 'JETHRO',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'COUNSEL', 'LEADERSHIP', 'PRIESTHOOD', 'WISDOM'],
  },
  {
    id: '8cb017e9c0be',
    name: 'JEZEBEL',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: [
      'AMBITION',
      'AUTHORITY',
      'BETRAYAL',
      'CONFLICT',
      'IDOLATRY',
      'KINGSHIP',
      'MANIPULATION',
      'POWER',
    ],
  },
  {
    id: '29ea81d0e0b7',
    name: 'JOB',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BLESSING', 'PATIENCE', 'SUFFERING'],
  },
  {
    id: 'c20704fb1bea',
    name: 'JOEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['HOPE', 'PROPHECY', 'WARNING'],
  },
  {
    id: '851f96ec7f08',
    name: 'JOHN',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'AMBITION',
      'COMMITMENT',
      'COURAGE',
      'DISCIPLE',
      'LOVE',
      'LOYALTY',
      'SPIRITUALITY',
      'VISIONS',
    ],
  },
  {
    id: 'e1c769752ded',
    name: 'JONAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DECISION', 'DISOBEDIENCE', 'MISSION', 'PROPHECY', 'REPENTANCE'],
  },
  {
    id: '10c05c683f7d',
    name: 'JOSEPH_NT',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['OBEDIENCE', 'VISIONS'],
  },
  {
    id: '495b93348c1b',
    name: 'JOSEPH_OT',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'BLESSING',
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'COUNSEL',
      'FORGIVENESS',
      'VISIONS',
      'WISDOM',
    ],
  },
  {
    id: '7365794cb3c6',
    name: 'JOSHUA',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'CHARISMA',
      'COMMITMENT',
      'CONFLICT',
      'COURAGE',
      'DECISION',
      'LEADERSHIP',
    ],
  },
  {
    id: 'e21370e773f1',
    name: 'JOSIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'KINGSHIP', 'REFORM', 'YOUTH'],
  },
  {
    id: '5eca9cdc4a28',
    name: 'JUDAS_THADDAEUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COURAGE', 'DISCIPLE', 'LOYALTY'],
  },
  {
    id: '434eb02d24ad',
    name: 'KORAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BETRAYAL', 'CONFLICT', 'JUDGMENT', 'PRIDE', 'REBELLION'],
  },
  {
    id: '536ad5ba5670',
    name: 'LAZARUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLE', 'LOYALTY', 'MIRACLE'],
  },
  {
    id: 'bedbe915403a',
    name: 'LOT',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['DECISION', 'SURVIVAL', 'WEAKNESS'],
  },
  {
    id: '6d9e91e15d40',
    name: 'LYDIA',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COMPASSION', 'GENEROSITY', 'HOSPITALITY'],
  },
  {
    id: 'fda9af972f06',
    name: 'MALACHI',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['JUSTICE', 'PROPHECY'],
  },
  {
    id: 'a06986d458ed',
    name: 'MANASSEH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'KINGSHIP', 'REPENTANCE', 'WICKEDNESS'],
  },
  {
    id: 'dce604085342',
    name: 'MARTHA',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLE', 'HOSPITALITY', 'SERVICE'],
  },
  {
    id: 'efc9ddc1f6cc',
    name: 'MARY',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['BLESSING', 'COMMITMENT', 'COMPASSION', 'DECISION', 'HUMILITY'],
  },
  {
    id: 'e61abe6f3157',
    name: 'MARY_MAGDALENE',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['CHARISMA', 'COMPASSION', 'DISCIPLE', 'LOYALTY'],
  },
  {
    id: '8835b91d22f0',
    name: 'MATTHEW',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DECISION', 'DISCIPLE', 'DISCIPLINE', 'TRANSFORMATION'],
  },
  {
    id: '0a6ac060fde8',
    name: 'MELCHIZEDEK',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'BLESSING', 'KINGSHIP', 'MYSTERY', 'PRIESTHOOD'],
  },
  {
    id: '8bb83ab2a1d5',
    name: 'MESHACH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'COURAGE', 'DELIVERANCE', 'LOYALTY'],
  },
  {
    id: 'b808bdd7b9ad',
    name: 'MICAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['JUSTICE', 'PROPHECY'],
  },
  {
    id: '83af57c8a569',
    name: 'MIRIAM',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['LEADERSHIP', 'PROPHECY', 'WORSHIP'],
  },
  {
    id: '04c018e95e56',
    name: 'MORDECAI',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'COUNSEL', 'COURAGE', 'DELIVERANCE', 'LOYALTY', 'WISDOM'],
  },
  {
    id: 'd66502bad9b3',
    name: 'MOSES',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'BLESSING',
      'CHARISMA',
      'COMPASSION',
      'CONFLICT',
      'COUNSEL',
      'DECISION',
      'DELIVERANCE',
      'LEADERSHIP',
      'PROPHECY',
      'VISIONS',
    ],
  },
  {
    id: '50b1fbe3df48',
    name: 'NAHUM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['JUDGMENT', 'JUSTICE', 'PROPHECY'],
  },
  {
    id: '33a8bfba05e6',
    name: 'NATHAN',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COUNSEL', 'COURAGE', 'PROPHECY'],
  },
  {
    id: 'e778ff0452e5',
    name: 'NEHEMIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'COMMITMENT', 'COMPASSION', 'CONFLICT', 'DISCIPLINE', 'LEADERSHIP'],
  },
  {
    id: '88e07349ecd3',
    name: 'NOAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BLESSING', 'COMMITMENT', 'DECISION', 'OBEDIENCE', 'PERSEVERANCE', 'WORK'],
  },
  {
    id: '53e291286051',
    name: 'OBADIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['BLESSING', 'COURAGE', 'LOYALTY', 'PROPHECY'],
  },
  {
    id: '40f7fe12dd90',
    name: 'ONESIMUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMPASSION', 'DELIVERANCE', 'REDEMPTION', 'TRANSFORMATION'],
  },
  {
    id: 'd713449b7477',
    name: 'PAUL',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'AUTHORITY',
      'CHARISMA',
      'COMMITMENT',
      'CONFLICT',
      'COUNSEL',
      'COURAGE',
      'DECISION',
      'DELIVERANCE',
      'DISCIPLE',
      'ELOQUENCE',
      'INTELLIGENCE',
      'MISSION',
      'VISIONS',
      'ZEAL',
    ],
  },
  {
    id: '4aeccfc45a8e',
    name: 'PETER',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'AUTHORITY',
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'CONFLICT',
      'COURAGE',
      'DELIVERANCE',
      'DISCIPLE',
      'IMPULSIVENESS',
      'LEADERSHIP',
      'VISIONS',
    ],
  },
  {
    id: '5376b95985f9',
    name: 'PHARAOH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AMBITION',
      'AUTHORITY',
      'CONFLICT',
      'KINGSHIP',
      'POWER',
      'PRIDE',
      'RESISTANCE',
      'VISIONS',
    ],
  },
  {
    id: 'c312c8d5b648',
    name: 'PHILEMON',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['FORGIVENESS', 'HOSPITALITY'],
  },
  {
    id: '7ea92a302845',
    name: 'PHILIP',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLE', 'EVANGELISM'],
  },
  {
    id: 'bab6c7139112',
    name: 'PILATE',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['AUTHORITY', 'CONFLICT', 'DECISION', 'WEAKNESS'],
  },
  {
    id: '7a3b0288b09d',
    name: 'PRISCILLA',
    gender: ['FEMALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'COUNSEL', 'LEADERSHIP', 'TEACHING'],
  },
  {
    id: 'd1a4727fefac',
    name: 'RAHAB',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'COMPASSION', 'COURAGE', 'REDEMPTION'],
  },
  {
    id: 'bb7b310e6e56',
    name: 'REBEKAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'INITIATIVE'],
  },
  {
    id: '1558fa7989ac',
    name: 'REHOBOAM',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'AUTHORITY', 'CONFLICT', 'DIVISION', 'KINGSHIP', 'LEADERSHIP', 'PRIDE'],
  },
  {
    id: '0a765194c58e',
    name: 'RUTH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BLESSING', 'COMPASSION', 'DECISION', 'LOVE', 'LOYALTY'],
  },
  {
    id: 'c93153fbd2ec',
    name: 'SAMSON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'CHARISMA', 'CONFLICT', 'COURAGE', 'SACRIFICE', 'WEAKNESS'],
  },
  {
    id: 'fd5e94014a42',
    name: 'SAMUEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'CHARISMA',
      'COUNSEL',
      'LEADERSHIP',
      'PRIESTHOOD',
      'PROPHECY',
      'VISIONS',
    ],
  },
  {
    id: 'c9260283e598',
    name: 'SARAH',
    gender: ['FEMALE'],
    age: ['OLD_AGE'],
    features: ['BEAUTY', 'BLESSING', 'MATERNITY', 'PATIENCE'],
  },
  {
    id: 'b00d1b737b0e',
    name: 'SAUL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AMBITION', 'AUTHORITY', 'BEAUTY', 'CONFLICT', 'KINGSHIP', 'PRIDE'],
  },
  {
    id: '1473e65b990d',
    name: 'SHADRACH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['COMMITMENT', 'CONFLICT', 'COURAGE', 'DELIVERANCE', 'LOYALTY'],
  },
  {
    id: '0242e2081a15',
    name: 'SILAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLE', 'MISSION', 'PERSEVERANCE'],
  },
  {
    id: 'ecab39db05b8',
    name: 'SIMON_ZEALOT',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'ZEAL'],
  },
  {
    id: 'd772d2b0ad91',
    name: 'SOLOMON',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: [
      'AUTHORITY',
      'BEAUTY',
      'BLESSING',
      'CHARISMA',
      'COUNSEL',
      'DECISION',
      'ELOQUENCE',
      'KINGSHIP',
      'WEALTH',
      'WISDOM',
    ],
  },
  {
    id: 'dd28adb09f3d',
    name: 'STEPHEN',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: [
      'CHARISMA',
      'COMMITMENT',
      'COMPASSION',
      'COURAGE',
      'DISCIPLE',
      'MARTYRDOM',
      'VISIONS',
    ],
  },
  {
    id: '3243634e124d',
    name: 'THOMAS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COURAGE', 'DOUBT'],
  },
  {
    id: '7f2e8ad692ec',
    name: 'TIMOTHY',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['COMMITMENT', 'DISCIPLE', 'YOUTH'],
  },
  {
    id: '9917fed6d108',
    name: 'TITUS',
    gender: ['MALE'],
    age: ['NEW_AGE'],
    features: ['DISCIPLINE', 'LEADERSHIP'],
  },
  {
    id: '78ef9851a10d',
    name: 'URIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['CONFLICT', 'HONOR', 'LOYALTY', 'SACRIFICE'],
  },
  {
    id: 'd8126ec3a1a1',
    name: 'ZECHARIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['HOPE', 'PRIESTHOOD', 'PROPHECY', 'VISIONS'],
  },
  {
    id: '5d817a26bc0e',
    name: 'ZEPHANIAH',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['JUDGMENT', 'PROPHECY', 'WARNING'],
  },
  {
    id: 'be620be58de8',
    name: 'ZERUBBABEL',
    gender: ['MALE'],
    age: ['OLD_AGE'],
    features: ['AUTHORITY', 'LEADERSHIP', 'RESTORATION'],
  },
]

export { persons }
