const locale = navigator.language || 'en-US'

const localization: Record<string, Record<string, string>> = {
  // PERSONAGENS
  AARON: { en: 'Aaron', es: 'Aarón', pt: 'Arão' },
  ABRAHAM: { en: 'Abraham', es: 'Abraham', pt: 'Abraão' },
  ADAM: { en: 'Adam', es: 'Adán', pt: 'Adão' },
  ANDREW: { en: 'Andrew', es: 'Andrés', pt: 'André' },
  BARTHOLOMEW: { en: 'Bartholomew', es: 'Bartolomé', pt: 'Bartolomeu' },
  CALEB: { en: 'Caleb', es: 'Caleb', pt: 'Calebe' },
  DANIEL: { en: 'Daniel', es: 'Daniel', pt: 'Daniel' },
  DAVID: { en: 'David', es: 'David', pt: 'Davi' },
  DEBORAH: { en: 'Deborah', es: 'Débora', pt: 'Débora' },
  ELIJAH: { en: 'Elijah', es: 'Elías', pt: 'Elias' },
  ELISHA: { en: 'Elisha', es: 'Eliseo', pt: 'Eliseu' },
  ESAU: { en: 'Esau', es: 'Esaú', pt: 'Esaú' },
  ESTHER: { en: 'Esther', es: 'Ester', pt: 'Ester' },
  EZEKIEL: { en: 'Ezekiel', es: 'Ezequiel', pt: 'Ezequiel' },
  EVE: { en: 'Eve', es: 'Eva', pt: 'Eva' },
  GIDEON: { en: 'Gideon', es: 'Gedeón', pt: 'Gideão' },
  HABAKKUK: { en: 'Habakkuk', es: 'Habacuc', pt: 'Habacuque' },
  ISAAC: { en: 'Isaac', es: 'Isaac', pt: 'Isaque' },
  ISAIAH: { en: 'Isaiah', es: 'Isaías', pt: 'Isaías' },
  JACOB: { en: 'Jacob', es: 'Jacob', pt: 'Jacó' },
  JAMES: { en: 'James', es: 'Santiago', pt: 'Tiago' },
  JEREMIAH: { en: 'Jeremiah', es: 'Jeremías', pt: 'Jeremias' },
  JESUS: { en: 'Jesus', es: 'Jesús', pt: 'Jesus' },
  JOB: { en: 'Job', es: 'Job', pt: 'Jó' },
  JOHN: { en: 'John', es: 'Juan', pt: 'João' },
  JOSEPH_NT: {
    en: 'Joseph (Jesus father)',
    es: 'José (padre de Jesús)',
    pt: 'José (pai de Jesus)',
  },
  JOSEPH_OT: { en: 'Joseph (from Egypt)', es: 'José (del Egipto)', pt: 'José (do Egito)' },
  JOSHUA: { en: 'Joshua', es: 'Josué', pt: 'Josué' },
  JUDAS_THADDAEUS: { en: 'Jude Thaddeus', es: 'Judas Tadeo', pt: 'Judas Tadeu' },
  LAZARUS: { en: 'Lazarus', es: 'Lázaro', pt: 'Lázaro' },
  LOT: { en: 'Lot', es: 'Lot', pt: 'Ló' },
  MARTHA: { en: 'Martha', es: 'Marta', pt: 'Marta' },
  MARY: { en: 'Mary', es: 'María', pt: 'Maria' },
  MARY_MAGDALENE: { en: 'Mary Magdalene', es: 'María Magdalena', pt: 'Maria Madalena' },
  MATTHEW: { en: 'Matthew', es: 'Mateo', pt: 'Mateus' },
  MIRIAM: { en: 'Miriam', es: 'Miriam', pt: 'Miriã' },
  MOSES: { en: 'Moses', es: 'Moisés', pt: 'Moisés' },
  NOAH: { en: 'Noah', es: 'Noé', pt: 'Noé' },
  OBADIAH: { en: 'Obadiah', es: 'Abadías', pt: 'Obadias' },
  PHILIP: { en: 'Philip', es: 'Felipe', pt: 'Filipe' },
  PAUL: { en: 'Paul', es: 'Pablo', pt: 'Paulo' },
  PETER: { en: 'Peter', es: 'Pedro', pt: 'Pedro' },
  RAHAB: { en: 'Rahab', es: 'Rahab', pt: 'Raabe' },
  REBEKAH: { en: 'Rebekah', es: 'Rebeca', pt: 'Rebeca' },
  RUTH: { en: 'Ruth', es: 'Rut', pt: 'Rute' },
  SAMSON: { en: 'Samson', es: 'Sansón', pt: 'Sansão' },
  SARAH: { en: 'Sarah', es: 'Sara', pt: 'Sara' },
  SIMON_ZEALOT: { en: 'Simon the Zealot', es: 'Simón el Zelote', pt: 'Simão, o Zelote' },
  SOLOMON: { en: 'Solomon', es: 'Salomón', pt: 'Salomão' },
  STEPHEN: { en: 'Stephen', es: 'Esteban', pt: 'Estevão' },
  TIMOTHY: { en: 'Timothy', es: 'Timoteo', pt: 'Timóteo' },
  TITUS: { en: 'Titus', es: 'Tito', pt: 'Tito' },
  THOMAS: { en: 'Thomas', es: 'Tomás', pt: 'Tomé' },
  ZEPHANIAH: { en: 'Zephaniah', es: 'Zefanías', pt: 'Zefanias' },
  SAUL: { en: 'Saul', es: 'Saúl', pt: 'Saulo' },
  SHADRACH: { en: 'Shadrach', es: 'Sadrac', pt: 'Sadraque' },
  MESHACH: { en: 'Meshach', es: 'Mesac', pt: 'Mesaque' },
  ABEDNEGO: { en: 'Abednego', es: 'Abednego', pt: 'Abednego' },
  MORDECAI: { en: 'Mordecai', es: 'Mardoqueo', pt: 'Mardoqueu' },
  NEHEMIAH: { en: 'Nehemiah', es: 'Nehemías', pt: 'Neemias' },
  EZRA: { en: 'Ezra', es: 'Esdras', pt: 'Esdras' },
  HAGGAI: { en: 'Haggai', es: 'Hageo', pt: 'Ageu' },
  ZECHARIAH: { en: 'Zechariah', es: 'Zacarías', pt: 'Zacarias' },
  MALACHI: { en: 'Malachi', es: 'Malaquías', pt: 'Malaquias' },
  JONAH: { en: 'Jonah', es: 'Jonás', pt: 'Jonas' },
  MELCHIZEDEK: { en: 'Melchizedek', es: 'Melquisedec', pt: 'Melquisedeque' },
  JETHRO: { en: 'Jethro', es: 'Jetro', pt: 'Jetro' },
  PHARAOH: { en: 'Pharaoh', es: 'Faraón', pt: 'Faraó' },
  BALAAM: { en: 'Balaam', es: 'Balaam', pt: 'Balaão' },
  KORAH: { en: 'Korah', es: 'Korah', pt: 'Korá' },
  ACHAN: { en: 'Achan', es: 'Acan', pt: 'Acã' },
  DELILAH: { en: 'Delilah', es: 'Dalila', pt: 'Dalila' },
  BATHSHEBA: { en: 'Bathsheba', es: 'Betsabé', pt: 'Bate-Seba' },
  URIAH: { en: 'Uriah', es: 'Urias', pt: 'Urias' },
  NATHAN: { en: 'Nathan', es: 'Natán', pt: 'Natã' },
  ABSALOM: { en: 'Absalom', es: 'Absalón', pt: 'Absalão' },
  REHOBOAM: { en: 'Rehoboam', es: 'Rehoboam', pt: 'Roboão' },
  JEROBOAM: { en: 'Jeroam', es: 'Jeroboam', pt: 'Jeroboão' },
  HEZEKIAH: { en: 'Hezekiah', es: 'Ezequías', pt: 'Ezequias' },
  MANASSEH: { en: 'Manasseh', es: 'Manasés', pt: 'Manassés' },
  AHAB: { en: 'Ahab', es: 'Acab', pt: 'Acabe' },
  JEZEBEL: { en: 'Jezebel', es: 'Jezabel', pt: 'Jezabel' },
  AMOS: { en: 'Amos', es: 'Amós', pt: 'Amós' },
  ZERUBBABEL: { en: 'Zerubbabel', es: 'Zerubabel', pt: 'Zerubabel' },
  ANNAS: { en: 'Annas', es: 'Anás', pt: 'Anás' },
  CAIAPHAS: { en: 'Caiaphas', es: 'Caifás', pt: 'Caifás' },
  PILATE: { en: 'Pilate', es: 'Pilato', pt: 'Pilatos' },
  BARNABAS: { en: 'Barnabas', es: 'Barnabás', pt: 'Barnabás' },
  SILAS: { en: 'Silas', es: 'Silas', pt: 'Silas' },
  LYDIA: { en: 'Lydia', es: 'Lidia', pt: 'Lídia' },
  PRISCILLA: { en: 'Priscilla', es: 'Priscila', pt: 'Priscila' },
  AQUILA: { en: 'Aquila', es: 'Aquila', pt: 'Aquila' },
  APOLLOS: { en: 'Apollonius', es: 'Apolonio', pt: 'Apólônio' },
  PHILEMON: { en: 'Philemon', es: 'Filemón', pt: 'Filemom' },
  ONESIMUS: { en: 'Onesimus', es: 'Onésimo', pt: 'Onésimo' },
  JOSIAH: { en: 'Josiah', es: 'Josías', pt: 'Josías' },

  // FEATURES
  SACRIFICE: { en: 'Sacrifice', es: 'Sacrificio', pt: 'Sacrifício' },
  LOVE: { en: 'Love', es: 'Amor', pt: 'Amor' },
  HOLINESS: { en: 'Holiness', es: 'Santidad', pt: 'Santidade' },
  LEADERSHIP: { en: 'Leadership', es: 'Liderazgo', pt: 'Liderança' },
  FAITH: { en: 'Faith', es: 'Fe', pt: 'Fé' },
  HUMILITY: { en: 'Humility', es: 'Humildad', pt: 'Humildade' },
  COMPASSION: { en: 'Compassion', es: 'Compasión', pt: 'Compaixão' },
  OBEDIENCE: { en: 'Obedience', es: 'Obediencia', pt: 'Obediência' },
  COURAGE: { en: 'Courage', es: 'Valentía', pt: 'Coragem' },
  WISDOM: { en: 'Wisdom', es: 'Sabiduría', pt: 'Sabedoria' },
  LOYALTY: { en: 'Loyalty', es: 'Lealtad', pt: 'Lealdade' },
  JUSTICE: { en: 'Justice', es: 'Justicia', pt: 'Justiça' },
  FORGIVENESS: { en: 'Forgiveness', es: 'Perdón', pt: 'Perdão' },
  PERSEVERANCE: { en: 'Perseverance', es: 'Perseverancia', pt: 'Perseverança' },
  PATIENCE: { en: 'Patience', es: 'Paciencia', pt: 'Paciência' },
  STRENGTH: { en: 'Strength', es: 'Fuerza', pt: 'Força' },
  WEAKNESS: { en: 'Weakness', es: 'Debilidad', pt: 'Fraqueza' },
  REPENTANCE: { en: 'Repentance', es: 'Arrepentimiento', pt: 'Arrependimento' },
  REDEMPTION: { en: 'Redemption', es: 'Redención', pt: 'Redenção' },
  TRUTH: { en: 'Truth', es: 'Verdad', pt: 'Verdade' },
  MALE: { en: 'Male', es: 'Masculino', pt: 'Masculino' },
  FEMALE: { en: 'Female', es: 'Femenino', pt: 'Feminino' },
  NEW_AGE: { en: 'New Age', es: 'Nueva Edad', pt: 'Nova Era' },
  OLD_AGE: { en: 'Old Age', es: 'Vieja Edad', pt: 'Era Antiga' },
  MODERN_AGE: { en: 'Modern Age', es: 'Edad Moderna', pt: 'Era Moderna' },

  // Game UI
  GENDER: { en: 'Gender', es: 'Género', pt: 'Gênero' },
  FEATURE: { en: 'Feature', es: 'Característica', pt: 'Característica' },
  AGE: { en: 'Age', es: 'Edad', pt: 'Era' },
  GAME_TITLE: { en: 'Who Am I?', es: '¿Quién Soy?', pt: 'Quem Sou Eu?' },

  // Game Messages
  GAME_DESCRIPTION: {
    en: 'Guess the character based on their traits and story.',
    es: 'Adivina el personaje basado en sus características e historia.',
    pt: 'Adivinhe o personagem com base em suas características e história.',
  },
  GAME_OVER_SUCCESS: {
    en: 'Congratulations! You guessed correctly!',
    es: '¡Felicidades! ¡Adivinaste correctamente!',
    pt: 'Parabéns! Você adivinhou corretamente!',
  },
  GAME_OVER_FAILURE: {
    en: 'Game Over! Better luck next time.',
    es: '¡Juego Terminado! Mejor suerte la próxima vez.',
    pt: 'Fim de Jogo! Melhor sorte na próxima vez.',
  },
  TRIES_LEFT: {
    en: 'Tries Left',
    es: 'Intentos Restantes',
    pt: 'Tentativas Restantes',
  },

  // Game Stats
  TOTAL_GAMES: {
    en: 'Total Games',
    es: 'Total de Juegos',
    pt: 'Total de Jogos',
  },
  GAMES_WON: {
    en: 'Games Won',
    es: 'Juegos Ganados',
    pt: 'Jogos Vencidos',
  },
  WIN_RATE: {
    en: 'Win Rate',
    es: 'Tasa de Victoria',
    pt: 'Taxa de Vitória',
  },
  CHART_TITLE: {
    en: 'Games Won by tries',
    es: 'Juegos Ganados por intentos',
    pt: 'Jogos Vencidos por tentativas',
  },
}

function t(name: string): string {
  const lang = locale.split('-')[0] || 'en'
  return localization[name]?.[lang] || name
}

export { t }
