const locale = navigator.language || 'en-US'

const localization: Record<string, Record<string, string>> = {
  // PERSONAGENS
  AARON: { en: 'Aaron', es: 'Aarón', pt: 'Arão' },
  ABRAHAM: { en: 'Abraham', es: 'Abraham', pt: 'Abraão' },
  ADAM: { en: 'Adam', es: 'Adán', pt: 'Adão' },
  ANDREW: { en: 'Andrew', es: 'Andrés', pt: 'André' },
  BARTHOLOMEW: { en: 'Bartholomew', es: 'Bartolomé', pt: 'Bartolomeu' },
  CALEB: { en: 'Caleb', es: 'Caleb', pt: 'Calebe' },
  DANIEL: { en: 'Daniel', es: 'Daniel', pt: 'Daniel' },
  DAVID: { en: 'David', es: 'David', pt: 'Davi' },
  DEBORAH: { en: 'Deborah', es: 'Débora', pt: 'Débora' },
  ELIJAH: { en: 'Elijah', es: 'Elías', pt: 'Elias' },
  ELISHA: { en: 'Elisha', es: 'Eliseo', pt: 'Eliseu' },
  ESAU: { en: 'Esau', es: 'Esaú', pt: 'Esaú' },
  ESTHER: { en: 'Esther', es: 'Ester', pt: 'Ester' },
  EZEKIEL: { en: 'Ezekiel', es: 'Ezequiel', pt: 'Ezequiel' },
  EVE: { en: 'Eve', es: 'Eva', pt: 'Eva' },
  GIDEON: { en: 'Gideon', es: 'Gedeón', pt: 'Gideão' },
  HABAKKUK: { en: 'Habakkuk', es: 'Habacuc', pt: 'Habacuque' },
  ISAAC: { en: 'Isaac', es: 'Isaac', pt: 'Isaque' },
  ISAIAH: { en: 'Isaiah', es: 'Isaías', pt: 'Isaías' },
  JACOB: { en: 'Jacob', es: 'Jacob', pt: 'Jacó' },
  JAMES: { en: 'James', es: 'Santiago', pt: 'Tiago' },
  JEREMIAH: { en: 'Jeremiah', es: 'Jeremías', pt: 'Jeremias' },
  JESUS: { en: 'Jesus', es: 'Jesús', pt: 'Jesus' },
  JOB: { en: 'Job', es: 'Job', pt: 'Jó' },
  JOHN: { en: 'John', es: 'Juan', pt: 'João' },
  JOSEPH_NT: {
    en: 'Joseph (Jesus father)',
    es: 'José (padre de Jesús)',
    pt: 'José (pai de Jesus)',
  },
  JOSEPH_OT: { en: 'Joseph (from Egypt)', es: 'José (del Egipto)', pt: 'José (do Egito)' },
  JOSHUA: { en: 'Joshua', es: 'Josué', pt: 'Josué' },
  JUDAS_THADDAEUS: { en: 'Jude Thaddeus', es: 'Judas Tadeo', pt: 'Judas Tadeu' },
  LAZARUS: { en: 'Lazarus', es: 'Lázaro', pt: 'Lázaro' },
  LOT: { en: 'Lot', es: 'Lot', pt: 'Ló' },
  MARTHA: { en: 'Martha', es: 'Marta', pt: 'Marta' },
  MARY: { en: 'Mary', es: 'María', pt: 'Maria' },
  MARY_MAGDALENE: { en: 'Mary Magdalene', es: 'María Magdalena', pt: 'Maria Madalena' },
  MATTHEW: { en: 'Matthew', es: 'Mateo', pt: 'Mateus' },
  MIRIAM: { en: 'Miriam', es: 'Miriam', pt: 'Miriã' },
  MOSES: { en: 'Moses', es: 'Moisés', pt: 'Moisés' },
  NOAH: { en: 'Noah', es: 'Noé', pt: 'Noé' },
  OBADIAH: { en: 'Obadiah', es: 'Abadías', pt: 'Obadias' },
  PHILIP: { en: 'Philip', es: 'Felipe', pt: 'Filipe' },
  PAUL: { en: 'Paul', es: 'Pablo', pt: 'Paulo' },
  PETER: { en: 'Peter', es: 'Pedro', pt: 'Pedro' },
  RAHAB: { en: 'Rahab', es: 'Rahab', pt: 'Raabe' },
  REBEKAH: { en: 'Rebekah', es: 'Rebeca', pt: 'Rebeca' },
  RUTH: { en: 'Ruth', es: 'Rut', pt: 'Rute' },
  SAMSON: { en: 'Samson', es: 'Sansón', pt: 'Sansão' },
  SARAH: { en: 'Sarah', es: 'Sara', pt: 'Sara' },
  SIMON_ZEALOT: { en: 'Simon the Zealot', es: 'Simón el Zelote', pt: 'Simão, o Zelote' },
  SOLOMON: { en: 'Solomon', es: 'Salomón', pt: 'Salomão' },
  STEPHEN: { en: 'Stephen', es: 'Esteban', pt: 'Estevão' },
  TIMOTHY: { en: 'Timothy', es: 'Timoteo', pt: 'Timóteo' },
  TITUS: { en: 'Titus', es: 'Tito', pt: 'Tito' },
  THOMAS: { en: 'Thomas', es: 'Tomás', pt: 'Tomé' },
  ZEPHANIAH: { en: 'Zephaniah', es: 'Zefanías', pt: 'Zefanias' },
  SAUL: { en: 'Saul', es: 'Saúl', pt: 'Saulo' },
  SHADRACH: { en: 'Shadrach', es: 'Sadrac', pt: 'Sadraque' },
  MESHACH: { en: 'Meshach', es: 'Mesac', pt: 'Mesaque' },
  ABEDNEGO: { en: 'Abednego', es: 'Abednego', pt: 'Abednego' },
  MORDECAI: { en: 'Mordecai', es: 'Mardoqueo', pt: 'Mardoqueu' },
  NEHEMIAH: { en: 'Nehemiah', es: 'Nehemías', pt: 'Neemias' },
  EZRA: { en: 'Ezra', es: 'Esdras', pt: 'Esdras' },
  HAGGAI: { en: 'Haggai', es: 'Hageo', pt: 'Ageu' },
  ZECHARIAH: { en: 'Zechariah', es: 'Zacarías', pt: 'Zacarias' },
  MALACHI: { en: 'Malachi', es: 'Malaquías', pt: 'Malaquias' },
  JONAH: { en: 'Jonah', es: 'Jonás', pt: 'Jonas' },
  MELCHIZEDEK: { en: 'Melchizedek', es: 'Melquisedec', pt: 'Melquisedeque' },
  JETHRO: { en: 'Jethro', es: 'Jetro', pt: 'Jetro' },
  PHARAOH: { en: 'Pharaoh', es: 'Faraón', pt: 'Faraó' },
  BALAAM: { en: 'Balaam', es: 'Balaam', pt: 'Balaão' },
  KORAH: { en: 'Korah', es: 'Korah', pt: 'Korá' },
  ACHAN: { en: 'Achan', es: 'Acan', pt: 'Acã' },
  DELILAH: { en: 'Delilah', es: 'Dalila', pt: 'Dalila' },
  BATHSHEBA: { en: 'Bathsheba', es: 'Betsabé', pt: 'Bate-Seba' },
  URIAH: { en: 'Uriah', es: 'Urias', pt: 'Urias' },
  NATHAN: { en: 'Nathan', es: 'Natán', pt: 'Natã' },
  ABSALOM: { en: 'Absalom', es: 'Absalón', pt: 'Absalão' },
  REHOBOAM: { en: 'Rehoboam', es: 'Rehoboam', pt: 'Roboão' },
  JEROBOAM: { en: 'Jeroam', es: 'Jeroboam', pt: 'Jeroboão' },
  HEZEKIAH: { en: 'Hezekiah', es: 'Ezequías', pt: 'Ezequias' },
  MANASSEH: { en: 'Manasseh', es: 'Manasés', pt: 'Manassés' },
  AHAB: { en: 'Ahab', es: 'Acab', pt: 'Acabe' },
  JEZEBEL: { en: 'Jezebel', es: 'Jezabel', pt: 'Jezabel' },
  AMOS: { en: 'Amos', es: 'Amós', pt: 'Amós' },
  ZERUBBABEL: { en: 'Zerubbabel', es: 'Zerubabel', pt: 'Zerubabel' },
  ANNAS: { en: 'Annas', es: 'Anás', pt: 'Anás' },
  CAIAPHAS: { en: 'Caiaphas', es: 'Caifás', pt: 'Caifás' },
  PILATE: { en: 'Pilate', es: 'Pilato', pt: 'Pilatos' },
  BARNABAS: { en: 'Barnabas', es: 'Barnabás', pt: 'Barnabás' },
  SILAS: { en: 'Silas', es: 'Silas', pt: 'Silas' },
  LYDIA: { en: 'Lydia', es: 'Lidia', pt: 'Lídia' },
  PRISCILLA: { en: 'Priscilla', es: 'Priscila', pt: 'Priscila' },
  AQUILA: { en: 'Aquila', es: 'Aquila', pt: 'Aquila' },
  APOLLOS: { en: 'Apollonius', es: 'Apolonio', pt: 'Apólônio' },
  PHILEMON: { en: 'Philemon', es: 'Filemón', pt: 'Filemom' },
  ONESIMUS: { en: 'Onesimus', es: 'Onésimo', pt: 'Onésimo' },
  JOSIAH: { en: 'Josiah', es: 'Josías', pt: 'Josías' },

  // FEATURES
  FEMALE: { en: 'Female', es: 'Femenino', pt: 'Feminino' },
  MALE: { en: 'Male', es: 'Masculino', pt: 'Masculino' },
  UNKNOWN: { en: 'Unknown', es: 'Desconocido', pt: 'Desconhecido' },
  NEW_AGE: { en: 'New Age', es: 'Nueva Edad', pt: 'Nova Era' },
  OLD_AGE: { en: 'Old Age', es: 'Vieja Edad', pt: 'Era Antiga' },
  MODERN_AGE: { en: 'Modern Age', es: 'Edad Moderna', pt: 'Era Moderna' },

  SACRIFICE: { en: 'Sacrifice', es: 'Sacrificio', pt: 'Sacrifício' },
  LOVE: { en: 'Love', es: 'Amor', pt: 'Amor' },
  HOLINESS: { en: 'Holiness', es: 'Santidad', pt: 'Santidade' },
  LEADERSHIP: { en: 'Leadership', es: 'Liderazgo', pt: 'Liderança' },
  FAITH: { en: 'Faith', es: 'Fe', pt: 'Fé' },
  HUMILITY: { en: 'Humility', es: 'Humildad', pt: 'Humildade' },
  COMPASSION: { en: 'Compassion', es: 'Compasión', pt: 'Compaixão' },
  OBEDIENCE: { en: 'Obedience', es: 'Obediencia', pt: 'Obediência' },
  COURAGE: { en: 'Courage', es: 'Valentía', pt: 'Coragem' },
  WISDOM: { en: 'Wisdom', es: 'Sabiduría', pt: 'Sabedoria' },
  LOYALTY: { en: 'Loyalty', es: 'Lealtad', pt: 'Lealdade' },
  JUSTICE: { en: 'Justice', es: 'Justicia', pt: 'Justiça' },
  FORGIVENESS: { en: 'Forgiveness', es: 'Perdón', pt: 'Perdão' },
  PERSEVERANCE: { en: 'Perseverance', es: 'Perseverancia', pt: 'Perseverança' },
  PATIENCE: { en: 'Patience', es: 'Paciencia', pt: 'Paciência' },
  STRENGTH: { en: 'Strength', es: 'Fuerza', pt: 'Força' },
  WEAKNESS: { en: 'Weakness', es: 'Debilidad', pt: 'Fraqueza' },
  REPENTANCE: { en: 'Repentance', es: 'Arrepentimiento', pt: 'Arrependimento' },
  REDEMPTION: { en: 'Redemption', es: 'Redención', pt: 'Redenção' },
  PRIESTHOOD: { en: 'Priesthood', es: 'Sacerdocio', pt: 'Sacerdócio' },
  KINGSHIP: { en: 'Kingship', es: 'Monarquía', pt: 'Realeza' },
  TRUTH: { en: 'Truth', es: 'Verdad', pt: 'Verdade' },
  VISIONS: { en: 'Visions', es: 'Visiones', pt: 'Visões' },
  AUTHORITY: { en: 'Authority', es: 'Autoridad', pt: 'Autoridade' },
  BLESSING: { en: 'Blessing', es: 'Bendición', pt: 'Bênção' },
  COUNSEL: { en: 'Counsel', es: 'Consejo', pt: 'Conselho' },
  PROPHECY: { en: 'Prophecy', es: 'Profecía', pt: 'Profecia' },
  SUPPORT: { en: 'Support', es: 'Apoyo', pt: 'Apoio' },
  COMMITMENT: { en: 'Commitment', es: 'Compromiso', pt: 'Compromisso' },
  CONFLICT: { en: 'Conflict', es: 'Conflicto', pt: 'Conflito' },
  DELIVERANCE: { en: 'Deliverance', es: 'Liberación', pt: 'Libertação' },
  CHARISMA: { en: 'Charisma', es: 'Carisma', pt: 'Carisma' },
  DECISION: { en: 'Decision', es: 'Decisión', pt: 'Decisão' },
  AMBITION: { en: 'Ambition', es: 'Ambición', pt: 'Ambição' },
  BEAUTY: { en: 'Beauty', es: 'Belleza', pt: 'Beleza' },
  BETRAYAL: { en: 'Betrayal', es: 'Traición', pt: 'Traição' },
  REBELLION: { en: 'Rebellion', es: 'Rebelión', pt: 'Rebelião' },
  DISOBEDIENCE: { en: 'Disobedience', es: 'Desobediencia', pt: 'Desobediência' },
  GREED: { en: 'Greed', es: 'Avaricia', pt: 'Ganância' },
  HUMANITY: { en: 'Humanity', es: 'Humanidad', pt: 'Humanidade' },
  IDOLATRY: { en: 'Idolatry', es: 'Idolatría', pt: 'Idolatria' },
  POWER: { en: 'Power', es: 'Poder', pt: 'Poder' },
  DISCIPLE: { en: 'Disciple', es: 'Discípulo', pt: 'Discípulo' },
  EVANGELISM: { en: 'Evangelism', es: 'Evangelización', pt: 'Evangelismo' },
  POLITICS: { en: 'Politics', es: 'Política', pt: 'Política' },
  RELIGION: { en: 'Religion', es: 'Religión', pt: 'Religião' },
  ELOQUENCE: { en: 'Eloquence', es: 'Elocuencia', pt: 'Eloquência' },
  TEACHING: { en: 'Teaching', es: 'Enseñanza', pt: 'Ensino' },
  PARTNERSHIP: { en: 'Partnership', es: 'Asociación', pt: 'Parceria' },
  WORK: { en: 'Work', es: 'Trabajo', pt: 'Trabalho' },
  ENCOURAGEMENT: { en: 'Encouragement', es: 'Ánimo', pt: 'Encorajamento' },
  MISSION: { en: 'Mission', es: 'Misión', pt: 'Missão' },
  HONESTY: { en: 'Honesty', es: 'Honestidad', pt: 'Honestidade' },
  MIRACLES: { en: 'Miracles', es: 'Milagros', pt: 'Milagres' },
  IMPULSIVENESS: { en: 'Impulsiveness', es: 'Impulsividad', pt: 'Impulsividade' },
  LOSS: { en: 'Loss', es: 'Pérdida', pt: 'Perda' },
  TEMPTATION: { en: 'Temptation', es: 'Tentación', pt: 'Tentação' },
  LAW: { en: 'Law', es: 'Ley', pt: 'Lei' },
  DOUBT: { en: 'Doubt', es: 'Duda', pt: 'Dúvida' },
  QUESTIONING: { en: 'Questioning', es: 'Cuestionamiento', pt: 'Questionamento' },
  MOTIVATION: { en: 'Motivation', es: 'Motivación', pt: 'Motivação' },
  PRAYER: { en: 'Prayer', es: 'Oración', pt: 'Oração' },
  REFORM: { en: 'Reform', es: 'Reforma', pt: 'Reforma' },
  PEACEFULNESS: { en: 'Peacefulness', es: 'Tranquilidad', pt: 'Tranquilidade' },
  TRANSFORMATION: { en: 'Transformation', es: 'Transformación', pt: 'Transformação' },
  MARTYRDOM: { en: 'Martyrdom', es: 'Martirio', pt: 'Martírio' },
  SORROW: { en: 'Sorrow', es: 'Tristeza', pt: 'Tristeza' },
  MANIPULATION: { en: 'Manipulation', es: 'Manipulación', pt: 'Manipulação' },
  SUFFERING: { en: 'Suffering', es: 'Sufrimiento', pt: 'Sofrimento' },
  HOPE: { en: 'Hope', es: 'Esperanza', pt: 'Esperança' },
  WARNING: { en: 'Warning', es: 'Advertencia', pt: 'Aviso' },
  SPIRITUALITY: { en: 'Spirituality', es: 'Espiritualidad', pt: 'Espiritualidade' },
  YOUTH: { en: 'Youth', es: 'Juventud', pt: 'Juventude' },
  JUDGMENT: { en: 'Judgment', es: 'Juicio', pt: 'Julgamento' },
  PRIDE: { en: 'Pride', es: 'Orgullo', pt: 'Orgulho' },
  MIRACLE: { en: 'Miracle', es: 'Milagro', pt: 'Milagre' },
  SURVIVAL: { en: 'Survival', es: 'Supervivencia', pt: 'Sobrevivência' },
  GENEROSITY: { en: 'Generosity', es: 'Generosidad', pt: 'Generosidade' },
  HOSPITALITY: { en: 'Hospitality', es: 'Hospitalidad', pt: 'Hospitalidade' },
  WICKEDNESS: { en: 'Wickedness', es: 'Maldad', pt: 'Maldade' },
  SERVICE: { en: 'Service', es: 'Servicio', pt: 'Serviço' },
  DISCIPLINE: { en: 'Discipline', es: 'Disciplina', pt: 'Disciplina' },
  MYSTERY: { en: 'Mystery', es: 'Misterio', pt: 'Mistério' },
  WORSHIP: { en: 'Worship', es: 'Adoración', pt: 'Adoração' },
  INTELLIGENCE: { en: 'Intelligence', es: 'Inteligencia', pt: 'Inteligência' },
  ZEAL: { en: 'Zeal', es: 'Celo', pt: 'Zelo' },
  RESISTANCE: { en: 'Resistance', es: 'Resistencia', pt: 'Resistência' },
  INITIATIVE: { en: 'Initiative', es: 'Iniciativa', pt: 'Iniciativa' },
  DIVISION: { en: 'Division', es: 'División', pt: 'Divisão' },
  MATERNITY: { en: 'Maternity', es: 'Maternidad', pt: 'Maternidade' },
  WEALTH: { en: 'Wealth', es: 'Riqueza', pt: 'Riqueza' },
  HONOR: { en: 'Honor', es: 'Honor', pt: 'Honra' },
  RESTORATION: { en: 'Restoration', es: 'Restauración', pt: 'Restauração' },

  // Game UI
  GENDER: { en: 'Gender', es: 'Género', pt: 'Gênero' },
  FEATURE: { en: 'Feature', es: 'Característica', pt: 'Características' },
FEATURES: { en: 'Features', es: 'Características', pt: 'Característica' },
  AGE: { en: 'Age', es: 'Edad', pt: 'Era' },
  GAME_TITLE: { en: 'Who Am I?', es: '¿Quién Soy?', pt: 'Quem Sou Eu?' },

  // Game Messages
  GAME_DESCRIPTION: {
    en: 'Guess the character based on their traits.',
    es: 'Adivina el personaje basado en sus características.',
    pt: 'Adivinhe o personagem com base em suas características.',
  },
  GAME_OVER_SUCCESS: {
    en: 'Congratulations! You guessed correctly!',
    es: '¡Felicidades! ¡Adivinaste correctamente!',
    pt: 'Parabéns! Você adivinhou corretamente!',
  },
  GAME_OVER_FAILURE: {
    en: 'Game Over! Better luck next time.',
    es: '¡Juego Terminado! Mejor suerte la próxima vez.',
    pt: 'Fim de Jogo! Melhor sorte na próxima vez.',
  },
  TRIES_LEFT: {
    en: 'Tries Left',
    es: 'Intentos Restantes',
    pt: 'Tentativas Restantes',
  },

  // Game Stats
  TOTAL_GAMES: {
    en: 'Total Games',
    es: 'Total de Juegos',
    pt: 'Total de Jogos',
  },
  GAMES_WON: {
    en: 'Games Won',
    es: 'Juegos Ganados',
    pt: 'Jogos Vencidos',
  },
  WIN_RATE: {
    en: 'Win Rate',
    es: 'Tasa de Victoria',
    pt: 'Taxa de Vitória',
  },
  CHART_TITLE: {
    en: 'Games Won by tries',
    es: 'Juegos Ganados por intentos',
    pt: 'Jogos Vencidos por tentativas',
  },
}

function t(name: string): string {
  const lang = locale.split('-')[0] || 'en'
  return localization[name]?.[lang] || name
}

export { t }
